name: GitHub integration with Allure TestOps

on:
  push:
    branches: [main]

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install and configure allurectl
        uses: allure-framework/setup-allurectl@v1.0.2
        with:
          allure-endpoint: https://softlabs.testops.cloud
          allure-project-id: 199
          allure-token: ${{ secrets.ALLURE_TOKEN }}
      - name: Build with Gradle and upload to Allure TestOps
        run: allurectl upload .
